### ISSUE TITLE
missed files

### ISSUE THREAD

**Issue by msorkhi** [tmedani/SIGMAbox#2]
hello Dr. Medani (@tmedani )
Thanks for helping.

for example, there is no file for sigma_install in the root as you mentioned in the manual book.
at the first step, there is no file ("Sigma_install") to run the project.
The first error is the Undefined function or variables like "Sigma_close_all_waitbar", "Sigma_install", "Sigma_freq_band_selection", and many files when we are going on the project when I track with my eyes.
It seems that the code is not the last version or something was wrong when you wanted to upload the code.

thanks to pay attention.
Maryam

**Comment by tmedani** [comment]
Hello Maryam, 
thanks for the reporting, indeed the version in the git is not the final version. 

I have updated the files and some data for tests. 

```
Sigma_install.m
SIGMA>> Installation in progress ... 
SIGMA>> You are running SIGMA under PC machine ...
SIGMA>> Adding SIGMA directory G:\My Drive\GitFolders\GitHub\SIGMAbox to your Matlab path ...
Sigma_gui.m
```

Could you check it again and let me know if you have further issues,

Best,

**Comment by tmedani** [comment]
Hello Maryam,

I have updated the files and some data for tests.

Sigma_install.m
SIGMA>> Installation in progress ... 
SIGMA>> You are running SIGMA under PC machine ...
SIGMA>> Adding SIGMA directory G:\My Drive\GitFolders\GitHub\SIGMAbox to your Matlab path ...
Sigma_gui.m
Could you check it again and let me know if you have further issues,

I'm closing this issue and keep discussing within the previous one.

Best,
